language: node_js

python:
  - "2.7"

node_js:
  - "12.14.1"

before_install:
  - python -v

install:
  - npm install --no-save eslint

script:
  - npm run lint

deploy:
  skip_cleanup: true
  provider: script
  script: node deploy.js
  on:
    branch: v5
