language: node_js
node_js:
  - "12.14.1"

cache:
  directories:
    - "node_modules"

install:
  - npm install -g grunt-cli node-gyp
  - cmd.exe /C 'for /f "delims=" %P in (\'npm prefix -g\') do npm config set node_gyp "%P\node_modules\node-gyp\bin\node-gyp.js"'
  - npm install

script:
  - npm run lint

deploy:
  skip_cleanup: true
  provider: script
  script: node deploy.js
  on:
    branch: v5
