language: node_js
node_js:
  - "12.14.1"

cache:
  directories:
    - "node_modules"

install:
  - npm install eslint

script:
  - npm run lint

deploy:
  skip_cleanup: true
  provider: script
  script: node deploy.js
  on:
    branch: v5
