language: node_js
node_js:
  - "12.14.1"

cache:
  directories:
    - "node_modules"

install:
  - npm install -g grunt-cli node-gyp@latest
  - npm list -g node-gyp
  - pwsh -Command npm config set node_gyp "`u{22}$(Join-Path $(npm prefix -g) -ChildPath 'node_modules/node-gyp/bin/node-gyp.js')`u{22}"
  - npm install

script:
  - npm run lint

deploy:
  skip_cleanup: true
  provider: script
  script: node deploy.js
  on:
    branch: v5
