language: node_js
node_js:
  - "12.14.1"

cache:
  directories:
    - "node_modules"

before_install:
  - npm install -g grunt-cli node-gyp@latest
  - npm list -g node-gyp
  - PREFIX="$(npm prefix -g)" && $(npm config set node_gyp "$PREFIX/node_modules/node-gyp/bin/node-gyp.js")
  - ls "/home/travis/.nvm/versions/node/v12.14.1/lib/node_modules/bin/"

install:
  - npm install

script:
  - npm run lint

deploy:
  skip_cleanup: true
  provider: script
  script: node deploy.js
  on:
    branch: v5
