name: Build and Draft Release

# Only runs
# - after PRs have been merged into master
# - when a user specifically requests the workflow to run on a branch
on:
  workflow_dispatch:
  push:
    branches: master

jobs:

  checkversion:
    name: Check if version has corrosponding tag
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      dobuild: ${{ steps.dobuild.outputs.dobuild }}

    steps:
      - name: Checkout crowbartools/firebot
        uses: actions/checkout@v3

      - name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Read package.json
        id: package
        uses: gregoranders/nodejs-project-info@v0.0.19

      - name: Retrieve package.json version
        id: version
        run: echo "version=${{ steps.package.outputs.version }}" >> $GITHUB_OUTPUT

      - name: 'Check: package version has corrosponding git tag'
        id: dobuild
        shell: bash
        run: echo dobuild=$(git show-ref --tags --verify --quiet -- "refs/tags/v${{ steps.version.outputs.version }}" && echo 0 || echo 1) >> $GITHUB_OUTPUT

  compile:
    name: 'Compile'
    needs: [checkversion]
    if: needs.checkversion.outputs.dobuild == 1
    strategy:
      matrix:
        os: [windows-2019, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install correct npm version
        run: npm install -g npm@8.16.0

      - name: Windows Build Prep
        if: runner.os == 'windows'
        shell: bash
        run: |
          npm config set msvs_version 2019
          npm install --quiet --global --production windows-build-tools@4.0.0

      - name: Linux Build Prep
        if: runner.os == 'linux'
        run: sudo apt-get install libx11-dev libxtst-dev libpng-dev

      - name: Install Global Dependencies
        run: npm install --quiet --global --production grunt-cli node-gyp

      - name: Install Project Dependencies
        run: npm ci --quiet

      - name: Rebuild Robotjs for electron
        run: npm run rebuild

      - name: Decrypt Secrets.gpg
        env:
          PASSKEY_FOR_FIREBOT_SECRETS: ${{ secrets.PASSKEY_FOR_FIREBOT_SECRETS }}
        run: grunt secrets:decrypt

      - name: Build for Platform
        run: grunt build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}
          path: ./dist/install/${{ runner.os == 'macOS' && 'darwin' || runner.os }}/

  draft:
    name: Draft Github Release
    needs: [checkversion, compile]
    if: needs.checkversion.outputs.dobuild == 1
    runs-on: ubuntu-latest
    steps:
      - name: Download Compilation Artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./bundles/

      - name: Rename Artifacts
        run: |
          cd bundles
          mv FirebotV5Setup.exe firebot-v${{ needs.checkoutversion.outputs.version }}-setup.exe
          mv Firebot-v${{ needs.checkoutversion.outputs.version }}-full.nupkg firebot-v${{ needs.checkoutversion.outputs.version }}-full.nupkg
          mv Firebot-linux-x64.tar.gz firebot-v${{ needs.checkoutversion.outputs.version }}-linux-x64.tar.gz
          mv Firebot.dmg firebot-v${{ needs.checkoutversion.outputs.version }}-macos-x64.dmg
          cd ..

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: $token
          draft: true
          prerelease: false
          tag_name: v${{ needs.checkoutversion.outputs.version }}
          release_name: Firebot v${{ needs.checkoutversion.outputs.version }}
          generate_release_notes: true
          body: '## v${{ steps.package.outputs.version }} Update Notes\n'
          files: |
            ./bundles/firebot-v${{ needs.checkoutversion.outputs.version }}-setup.exe
            ./bundles/firebot-v${{ needs.checkoutversion.outputs.version }}-full.nupgk
            ./bundles/RELEASES
            ./bundles/firebot-v${{ needs.checkoutversion.outputs.version }}-linux-x64.tar.gz
            ./bundles/firebot-v${{ needs.checkoutversion.outputs.version }}-macos-x64.dmg
