name: Test and Pack for Windows

on:
  push:
    branches:
      - master
      - v5

jobs:
  test:
    name: Test and Pack
    runs-on: 'windows-latest'
    steps:

      # Testing setup
      
      - name: Checkout branch that caused the job to run
        uses: 'actions/checkout@v2'

      - name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          
      - name: Setup Nodejs
        uses: 'actions/setup-node@v1'
        with:
          node-version: "10.x"

      - name: Install Testing Dependencies
        run: npm install --global --production eslint@^5.16.0 node-sass@^4.13.1

      - name: Run Linter
        run: eslint . --quiet
      
      - name: Compile scss into css
        run: |
          node-sass --quiet --source-map=false ./gui/scss/ --output=./gui/css
          node-sass --quiet --source-map=false ./resources/overlay/scss/ --output=./resources/overlay/css/

      # Prebuild checks

      - name: Read package.json
        id: package
        uses: gregoranders/nodejs-project-info@v0.0.1

      - name: 'Check: package version has corrosponding git tag'
        id: tagged
        run: git show-ref --tags --verify -- "refs/tags/v${{ steps.package.outputs.version }}"

      # Prep Build Enviornment

      - name: Setup Python
        if: github.ref == '/refs/heads/master' && failure()'
        uses: 'actions/setup-python@v1'
        with:
          python-version: '2.7'

      - name: Setup Windows Build Tools
        if: github.ref == '/refs/heads/master' && steps.tagged.status == 'failure'
        run: npm install --global --production windows-build-tools@4.0.0

      - name: Prep for node-gyp
        if: github.ref == '/refs/heads/master' && steps.tagged.status == 'failure'
        run: npm config set msvs_version 2015

      - name: Install node-gyp
        if: github.ref == '/refs/heads/master' && steps.tagged.status == 'failure'
        run: npm install --global --production node-gyp

      - name: Install Dependencies
        if: github.ref == '/refs/heads/master' && steps.tagged.status == 'failure'
        run: npm install

      # Build from Windows x64

      - name: Rebuild RobotJs for Electron 7.1.9
        if: github.ref == '/refs/heads/master' && steps.tagged.status == 'failure'
        run: 'node-gyp rebuild --directory=node_modules/robotjs/ --runtime=electron --target=7.1.9 --arch=x64 --dist-url=https://atom.io/download/atom-shell'

      - name: Build Windows Installer
        if: github.ref == '/refs/heads/master' && steps.tagged.status == 'failure'
        run: |
          grunt shell:packwin64
          grunt xcopy:win64
          grunt shell:create-windows-installer:win64