name: Firebot Testing

on:
  push:
    branches:
      - master
      - v5

jobs:
  test:
    name: Lint and SCSS tests
    runs-on: 'windows-latest'
    steps:
      - name: Checkout branch that caused the job to run
        uses: 'actions/checkout@v2'
      
      - name: Setup Python
        uses: 'actions/setup-python@v1'
        with:
          python-version: "2.7"
          
      - name: Setup Nodejs
        uses: 'actions/setup-node@v1'
        with:
          node-version: "10.x"

      - name: Setup Windows Build Tools
        run: npm install --global --production windows-build-tools@4.0.0
      
      - name: Prep for node-gyp
        run: npm config set msvs_version 2015
      
      - name: Install node-gyp
        run: npm install --global --production node-gyp

      - name: Install dependencies
        run: npm install

      - name: Run Linter
        run: npx eslint . --quiet
      
      - name: Compile scss into css
        run: |
          npx node-sass --quiet --source-map=false ./gui/scss/ --output=./gui/css
          npx node-sass --quiet --source-map=false ./resources/overlay/scss/ --output=./resources/overlay/css/

  winbuild:
    name: Build Windows installer
    runs-on: "windows-latest"
    needs: test # Only run job if test completes successfully
    if: github.ref == 'refs/heads/master' # Only run job on master branch
    steps:
      - name: Checkout master branch
        uses: 'actions/checkout@v2'

      - name: Setup Python
        uses: 'actions/setup-python@v1'
        with:
          python-version: "2.7"
          
      - name: Setup Nodejs
        uses: 'actions/setup-node@v1'
        with:
          node-version: "10.x"

      - name: Setup Windows Build Tools
        run: npm install --global --production windows-build-tools@4.0.0
      
      - name: Prep for node-gyp
        run: npm config set msvs_version 2015
      
      - name: Install grunt-cli and node-gyp
        run: npm install --global --production grunt-cli node-gyp

      - name: Install dependencies
        run: npm install

      - name: Rebuild RobotJs for Electron 7.1.9
        run: 'node-gyp rebuild --directory=node_modules/robotjs/ --runtime=electron --target=7.1.9 --arch=x64 --dist-url=https://atom.io/download/atom-shell'

      - name: Build Windows Installer
        run: grunt compile:win64

      - name: Store Installer
        uses: 'actions/upload-artifact@v1'
        with:
          name: 'win-installer'
          path: '/dist/install/win64/'


  linuxbuild:
    name: Build Linux Tarball
    runs-on: "ubuntu-latest"
    needs: test # Only run job if test completes successfully
    if: github.ref == 'refs/heads/master' # Only run job on master branch
    steps:
      - name: Checkout master branch
        uses: 'actions/checkout@v2'

      - name: Setup Python
        uses: 'actions/setup-python@v1'
        with:
          python-version: "2.7"
          
      - name: Setup Nodejs
        uses: 'actions/setup-node@v1'
        with:
          node-version: "10.x"


  draftrelease:
    name: Draft Release
    runs-on: "ubuntu-latest"
    needs: [winbuild, linuxbuild] # Only run job if building completes
    if: github.ref == 'refs/heads/master' # Only run job on master branch
    steps:
      - name: Get Windows Installer
        uses: 'actions/download-artifact@v1'
        with:
          name: 'win-installer'

      - name: Get Linux Bundle
        uses: 'actions/download-artifact@v1'
        with:
          name: 'linux-bundle'
