name: "firebot v5 lint"

on:
  push:
    branches:
      - master

jobs:
  test:
    name: "Lint"
    runs-on: "windows-latest"
    steps:

      # clone the repo's master branch
      - uses: "actions/checkout@v2"
          
      # install nodejs and npm
      - uses: "actions/setup-node@v1"
        with:
          node-version: "10.x"

      # install eslint
      - run: "npm install -g eslint@^5.16.0"

      # run eslint
      - run: "eslint . --quiet"
