name: "firebot v5 lint"

on:
  push:
    branches:
      - master

jobs:
  test:
    name: "Lint"
    runs-on: "windows-latest"
    steps:
      # clone the repo v5 branch
      - uses: "actions/checkout@master"
        with:
          fetch-depth: 1
          
      # install nodejs and npm
      - uses: "actions/setup-node@v1"
        with:
          node-version: "10.x"

      # install project dependencies
      - run: "npm install -g eslint@^5.16.0"

      # run linter
      - run: "npx eslint . --quiet"
